version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: book
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p1234"]
      timeout: 20s
      retries: 10


  springboot-app:
    container_name: spring-app
    image: rahulcena/user-registration-realtime:v1
    restart: on-failure
    build: .
    ports:
      - "8181:9090"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306    # we are in same network so we connect internally.
    depends_on:
      mysqldb:
        condition: service_healthy